Factorized various eval_as_xxx into a single eval_as template method
giubacc/chatterbox pull request #1
Opened 2022-11-30 17:46 UTC by biagiop1986

I factorized three different similar eval_as_xxx methods into a single template eval_as.

2022-12-01 08:34 UTC, giubacc commented
Hello @biagiop1986! Many thanks for your contribution!
The patch you are proposing is of the highest quality! :top: :top: :top:

Let's try to get rid of the things that must be corrected:

- `commit signature`: you are committing without a proper signature. Please, take a look [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification). The best option is that you generate a new GPG key and you upload the public key on a public key server.
- `Lint` check is failing. You can check details by clicking on the relevant CI item. The problem is that there are some trailing whitespaces, you should format source files with [astyle](https://astyle.sourceforge.net/). Most distributions provide directly the package. Once you have installed it, you should use the [config](https://github.com/giubacc/chatterbox/blob/6c680462990c2cfa03e1e9b04a92b8e389024032/src/.astylerc) file under src and execute: 
```
cd ${workspaceFolder}/src && astyle --project=.astylerc *.cpp *.h
```
- `Build` CI item is failing. This happens because currently the CI is not properly configured to handle correctly contributions. The problem is that  [build-builder.yaml](https://github.com/giubacc/chatterbox/blob/6c680462990c2cfa03e1e9b04a92b8e389024032/.github/workflows/build-builder.yaml) is currently configured to run on Sunday night. Because you opened this PR before this event ever run on your forked repository, there is no such image that CI can use to build `chatterbox`. A possible workaround to this could be that you try to build the `builder` image on your machine and then you push it on github. Let's take this issue for last.

2022-12-05 08:32 UTC, giubacc commented
@biagiop1986 you need to sync your fork and then rebase against main.
Now you have the `chatterbox-builder` image available, so CI should not be broken anymore.

2022-12-05 10:49 UTC, biagiop1986 commented
> @biagiop1986 you need to sync your fork and then rebase against main. Now you have the `chatterbox-builder` image available, so CI should not be broken anymore.

Thank you, done right now! I'm going to open a new pull request.

2022-12-05 17:35 UTC, giubacc requested changes
just a small fix; otherwise LGTM

2022-12-05 17:35 UTC, giubacc commented on src/chatterbox.h
> +    return val->IsUint32();
```suggestion
    return val->IsString();
```

2022-12-05 18:11 UTC, biagiop1986 commented on src/chatterbox.h
> +    return val->IsUint32();
Fixed!

2022-12-06 08:06 UTC, giubacc commented
please, squash the 2 commits, no need to co-author the latest commit.

2022-12-06 09:51 UTC, biagiop1986 commented
> please, squash the 2 commits, no need to co-author the latest commit.

Done!

2022-12-06 10:18 UTC, merged

2022-12-06 10:18 UTC, giubacc commented
thanks! merged :100: